services:
  billings-management-discovery-service:
    build: ./discovery-service
    container_name: billings-management-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      retries: 4
  billings-management-config-service:
    build: ./config-service
    container_name: billings-management-config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    environment:
      - DISCOVERY_SERVICE_URL=http://billings-management-discovery-service:8761/eureka
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      enset-ebank-discovery-service:
        condition: service_healthy
  billings-management-customer-service:
    build: ./customer-service
    container_name: enset-customer-service
    ports:
      - '8081:8081'
    expose:
      - '8081'
    environment:
      - DISCOVERY_SERVICE_URL=http://billings-management-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://billings-management-config-service:9999
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      billings-management-config-service:
        condition: service_healthy
  billings-management-product-service:
    build: ./products-service
    container_name: billings-management-product-service
    ports:
      - '8084:8084'
    expose:
      - '8084'
    environment:
      - DISCOVERY_SERVICE_URL=http://billings-management-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://billings-management-config-service:9999
    depends_on:
      billings-management-config-service:
        condition: service_healthy
  billings-management-gateway-service:
    build: ./gateway-service
    container_name: enset-gateway-service
    ports:
      - '8887:8887'
    expose:
      - '8887'
    environment:
      - DISCOVERY_SERVICE_URL=http://billings-management-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://billings-management-config-service:9999
    depends_on:
      billings-management-config-service:
        condition: service_healthy
  billings-management-billing-service:
    build: ./billing-service
    container_name: billings-management-billing-service
    ports:
      - '8095:8095'
    expose:
      - '8095'
    environment:
      - DISCOVERY_SERVICE_URL=http://billings-management-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://billings-management-config-service:9999
    depends_on:
      billings-management-customer-service:
        condition: service_healthy